#!/usr/bin/env bash

progress-bar() {
	local duration=${1}


	already_done() { for ((done=0; done<$elapsed; done++)); do printf "▇"; done }
	remaining() { for ((remain=$elapsed; remain<$duration; remain++)); do printf " "; done }
	percentage() { printf "| %s%%" $(( (($elapsed)*100)/($duration)*100/100 )); }
	clean_line() { printf "\r"; }

	for (( elapsed=1; elapsed<=$duration; elapsed++ )); do
	already_done; remaining; percentage
	sleep 1
	clean_line
	done
	clean_line
}

prefix="/usr/local"
name="createmf"

Install()
{
	echo "Installing $1 ...";
	cd $name || return 1;
	chmod a+x $1;
	progress-bar 4;
	if  cp $1 $prefix/bin > /dev/null 2>&1;
	then
	echo "Successfully installed.";
	cd .. || return 1
	echo "Thanks for using my program.";
	else
	echo "Cannot install script. Try installing the script as sudo."
	cd ..
	exit 1;
	fi
}

Update()
{
	echo "Updating $1 ...";
	progress-bar 4;
	git pull > /dev/null || return 1;
	echo "Update finished."
	Install $name;
}

usage()
{
	cat << EOF
Options:
	-h      Open this helper page
	-u      Update the script

Report bugs to tyler.t.nguyen@uconn.edu.
EOF
}

if [ -z $1 ]; then
	read -p "Do you want to install $name? [Y/n] " answer;
	case $answer in
	[Yy]* ) Install $name;
	esac
fi

while getopts ":hu" opt; do
	case $opt in
	h) usage;
	exit 0;
	;;
	u) Update;
	;;
	\?) echo "Invalid option: $OPTARG" >&2;
	usage;
	exit 1;
	;;
	esac
done
